geekquad/AlgoBook

python/graph_algorithms/dijkstra_shortest_path.py, python/graph_algorithms/floyd_warshall.py
Implemented Dijkstra’s shortest path algorithm and Floyd Warshall Algorithm in python.
=> Graph Algorithms

python/sorting/Piegon Sort.py
=> Adding Pigeon Sort

python/graph_algorithms/A-star_algorithm.py
Added the python file with code for A* Algorithm
=> added code for A* Algorithm

python/matrix/sherman_morrison.py
Adding Sherman Morrison algorithm in Python
=> Adding Sherman_Morisson

python/sorting/insertion_sort.py
Added Recursive Insertion Sort in Python
=> Added Recursive Insertion Sort #8

python/Matrix/count_islands.py
Added a python file with the code for Counting Islands in a Matrix
=> add code for Count Islands in Matrix in Python

python/searching/binarysearch.py, python/searching/linearsearch.py
I wish to contribute to this repository
=> Added linearsearch and binarysearch algorithms

python/Matrix/Spiral_Print.py
Added printing Matrix in Spiral in Python
=> Added printing Matrix in Spiral #20

python/searching/ternary_search.py, python/sorting/bead_sort.py
* Searching
> Open Source is not just about code, it is about communication collaboration
*By Siddhant Khare*
=> Ternary Search and Bead Sort

python/sorting/recursive_bubble_sort.py
issue #8 
Added file in sorting folder - recursive_bubble_sort.py
=> Added Recursive bubble sort 

ml/KNN/KNN.ipynb, ml/KNN/requirements.txt
Added implementation of KNN Supervised Machine Learning Algorithm
=> Added KNN #2

python/sorting/external_sort.py, python/sorting/stooge_sort.py
Implemented external algorithm in python
=> external_sort.py

python/sorting/external_sort.py, python/sorting/stooge_sort.py
Implemented Stooge Sort algorithm in python
=> Stooge_Sort 

python/sorting/PancakeSort.py
=> Intermediate Sorting Algorithms in Python #8

python/searching/interpolation.py
Add python code for interpolation search technique to the searching folder.
=> Add Interpolation.py 

python/sorting/wiggle_sort.py
Implementation of wiggle sort algorithm
=> wiggle sort

python/sorting/bitonic_sort.py, python/sorting/comb_sort.py
=> Bitonic & Comb Sort

python/Matrix/sorting_a_matrix.py, python/sorting/Bubble Sort.py
User can input the number of rows and columns and then can sort the matrix in ascending order
=> Sorting a Matrix 

python/graph_algorithms/kruskal_minimum_spanning_tree_algorithm.py
Added Kruskal's minimum spanning tree algorithm
=> Added kruskal_minimum_spanning_tree_algorithm

python/greedy_alogrithms/egyptian_franction.py
=> Egyptian fractions

python/sorting/bubble_sort.py
Implementation of bubble sort in Python.
=> 💧 Added bubble sort code (bubble_sort.py)

python/Stack/Stack.py, python/Stack/Valid Parantheses.py
Stack implementation using list in Python
=> Created Stack.py

python/graph_algorithms/Dijkstra's_Shortest_Path_Implementation_using_Adjacency_List.py
Added Dijkstras Shortest Path Algorithm using Adjacency List under Graph Algorithms
=> Added Dijkstras Shortest Path Algorithm using Adjacency List

python/Binary Tree/binary_tree_traversal.py, python/Binary Tree/fenwick_tree.py
Added Binary Tree Traversals and Fenwick Tree Implementation
Issue #119
=> Added Binary Tree Traversal and Fenwick Tree

.gitignore, python/Linked List/Doubly_LinkedList.py
This PR is for #120 
- added doubly linked list
- added a `.gitignore` file to ignore `.vscode` folder
=> Added doubly linked list

python/string algorithms/anagrams.py
Contribution for "Checking Anagrams in Python"
=> Issue #113 Checking Anagrams in Python

python/binary_trees/red-black.py
Implemented red-black in python
=> RED-BLACK IN PYTHON

python/sorting/selection_sort.py
I'm adding a Selection Sort Python implementation
=> Add Selection Sort

python/Matrix/Bullet-Brick.py
=> Added Bullet-Brick Problem

python/string algorithms/boyer_moore_sunday.py
this code allows count the repeting pattern  in the text, for more information enter in the next link  [https://www.inf.fh-flensburg.de/lang/algorithmen/pattern/sundayen.htm](url)
=> added the algorithm boyer moore sunday  

Shell Sort
The idea of shellSort is to allow exchange of far items. In shellSort, we make the array h-sorted for a large value of h. We keep reducing the value of h until it becomes 1. An array is said to be h-sorted if all sublists of every h’th element is sorted.
=> Shell Sort Algorithm

python/Linked List/Circular_LinkedList.py
=> added circular linked list

python/maths/lowest_common_multiple.py
The PR contains a lowest_common_multiple.py file .
Input Format :
- Two space-separated numbers.  
Output Format :
- Lowest Common Multiple : (calculated LCM)
=> Created the lowest_common_multiple.py

python/Matrix/magic_square.py
=> Added magic square

ml/Perceptrons/softmax.py
Added the softmax function in ML stack.
=> Softmax function

python/distance/HaversineDistanceInMiles.py
This is the Haversine lat/long distance algorithm. You can choose to use miles or kilometers in the function arguments.
=> Add Haversine lat/long distance algorithm

python/Queue/priority_queue.py, python/Queue/queue.py
Hello, I have implemented the Queue and Priority Data Structure. Let's discuss the improvements.
=> Implementation of Queue Data Structure

cpp/searching/breadth_first_search.cpp
Added breadth_first_search in CPP
=> Added breadth_first_search.cpp

cpp/searching/depth_first_search.cpp
Added depth-first search in cpp.
=> Added depth_first_search.cpp

cpp/sorting/merge_sort.cpp
=> Added merge_sort.cpp

cpp/sorting/Bucket Sort.cpp
=> Create Bucket Sort.cpp

ml/Perceptrons/Perceptron_NOT_Gate.ipynb, ml/Perceptrons/Perceptron_OR_Gate.ipynb
Solution for #239 
**I have added the *from scratch* implementations of perception algorithm to act as OR and NOT gates, as assigned [here](https://github.com/geekquad/AlgoBook/issues/239#issuecomment-704922695)** 
> Willing to contribute more on ML problems. Thanks.
=> Perceptron Implementation for OR and NOT gates

cpp/searching/binarysearch.cpp, cpp/searching/linearsearch.cpp
Added binary search using cpp
fixed issue: #237
=> Added binary search

cpp/searching/JumpSearch.cpp
Like Binary Search, Jump Search is a searching algorithm for sorted arrays. The basic idea is to check fewer elements (than linear search) by jumping ahead by fixed steps or skipping some elements in place of searching all elements.
For example, suppose we have an array arr[] of size n and block (to be jumped) size m. Then we search at the indexes arr[0], arr[m], arr[2m]…..arr[km] and so on. Once we find the interval (arr[km] < x < arr[(k+1)m]), we perform a linear search operation from the index km to find the element x. 
The following code illustrates the same.
=> Added code for Jump Search IN CPP

python/Matrix/strassen's_matrix_multiplication.py
=> Added strassen's matrix multiplication

python/dynamic_programming/coin_change.py
Added the code for "The coin change problem" solved from HackerRank. Please review and merge the pull request.
=> The coin change problem solution

cpp/sorting/ShellSort.cpp
Description - Added shell sort in C++
=> Shell Sort in C++

cpp/sorting/Tree_Sort.cpp, cpp/sorting/wiggle_sort.cpp
Implementation of a tree sort & wiggle Sort algorithm in C++
=> Kushagra: Implemented the tree sort and wiggle Sort in c++

cpp/Graphs/Breadth_First_Search.cpp, cpp/Graphs/Depth_First_Search.cpp
Added Algo implementations for Graphs in C++ as there was nothing like that in past.
-Added Depth First Search.
-Added Breadth First Search.
-Readed Repo's contibution guidelines and followed everywhere possible in code.
=> Added DFS and BFS implementation in Graphs

cpp/sorting/InsertionSort.cpp
=> Added Insertion Sort

python/sorting/Recursive_quick_sort.py
Added Recursive Quick Sort in Python
#8
=> Added Recursive Quick Sort in Python

cpp/sorting/Comb_Sort.cpp
Implementation of the Comb Sort in C++
=> Implemented the Comb Sort in C++

cpp/sorting/Bogo_Sort.cpp
=> Added Bogo Sort in C++

python/sorting/recursive_insertion_sort.py
=> Added Recursive Insertion Sort in python 

cpp/searching/interpolationSearch.cpp, cpp/sorting/bead_sort.cpp
Implemented the Bead Sort in C++
=> Added the Bead Sort & Interpolation Search Algorithm in C++

cpp/sorting/selection_sort.cpp
=> Added Selection sort

python/Matrix/Markov's_Chain.py, python/Matrix/Matrix-Add-Sub.py, python/Matrix/rotate_matrix.py, python/Matrix/sherman_morrison.py
Performed the following tasks in this pull request:
- Performed migration of codes, on redundant 'matrix' and 'Matrix' folder to 'Matrix' alone.
- Added Markov's Chain implementation in python
- Added matrix Addition and Subtraction implementation in python.
=> Added implementations and migrations in python

cpp/searching/Ternary_Search.cpp
Implemented Ternary Search Algo in C++
=> Added Ternary Search Algorithm in C++

python/dynamic_programming/minimum_insertions_deletions.py
transform str1 to str2 with a minimum number of insertions and deletions
=> add dp problem min insertions and deletions

cpp/dynamic_programming/TSP Genetic.cpp
Travelling Salesman Problem using Genetic Algorithm in C++.
=> Create TSP Genetic.cpp

cpp/dynamic_programming/number_of_prime_subarrays.cpp
Added number of prime subarrays problem in dynamic programming folder under cpp. This problem is asked in many coding interviews.
=> Number of prime subarrays problem

go/sorting/Bogosort/bogosort.go, go/sorting/Bubblesort/bubblesort.go, go/sorting/InsertionSort/insertionsort.go
Since the repo, as it is, has no implementation in GO, I thought to try to add some.
In particular, I've added three simple sorting algorithms.
If this is ok for you we can try to add also other languages to the repo! let me know what do you think
=> Adding sorting algorithms written in GO

Linear Search (Python).ipynb, Ugly Number.ipynb, Volume of 3D shapes.ipynb
cube, cuboid, cone, right circular cone, prism, pyramid, sphere, circular cylinder
=> Added volume of 3D shapes in python

python/graph_algorithms/Steiner Tree.py
=> steiner tree implementation python

python/graph_algorithms/Boruvka algorithm for Minimum Spanning Tree.py
=> boruvka algorithm to find minimum spanning

python/graph_algorithms/Karps minimum mean weight cycle algorithm.py
=> karps minimum mean weight cycle algorithm

cpp/sorting/Stooge Sort.cpp
=> stooge sort algo

go/dynamic_programming/kadane_algorithm.go, go/graph_algorithms/breadth_first_search.go, go/graph_algorithms/count_connected_components.go, go/graph_algorithms/depth_first_search.go
Added following Go implementations:
- Kadane's Algorithm (DP)
- DFS 
- BFS
- Connected components
=> Added Graph and DP Algorithms in Go language

go/dynamic_programming/coin_change.go, go/dynamic_programming/longest_common_subsequence.go
Added following implementations in Go:
- Coin Change
- LCS (Longest Common Subsequence)
=> Add Coin Change and LCS implementation in Go

python/Binary Tree/non_recursive_segment_tree.py
Implements Non Recursive Segment Tree from #119
=> Add Python non recursive segment array example

python/sorting/bucket_sort.py
This adds the Bucket Sort requirement for #8
=> Add Python bucket sort implementation

cpp/maths/Extnd_Euclidean_Algo.cpp, cpp/maths/Greatest_Common_Divisor.cpp, cpp/searching/Z_algorithm.cpp
Hey!
Added the Z Algorithm and the math problems in cpp. please check.
=> Z-Algorithm w/ Math cpp(gcd,extended euclidean algo) added

cpp/backtracking/Magnet_Puzzle.cpp, cpp/binary_tree/Recursive_Binary_search.cpp, cpp/maths/Extnd_Euclidean_Algo.cpp, cpp/maths/Greatest_Common_Divisor.cpp, cpp/searching/Z_algorithm.cpp
hey!
commited the Recursive Binary search and magnet puzzle in their respective folder.
=> cpp/Binary search/Recursive Binary search and backtracking/magnet puzzle

cpp/maths/Peterson_number.cpp, cpp/maths/Pythagoras.cpp
issue #197 
Peterson Number
Pythagoras implementation
added in C++
=> peterson number and pythagoras theorem added

python/string algorithms/rabinKarp.py
Implementation of Rabin-Karp Algorithm in Python
=> Rabin-Karp Algorithm

cpp/maths/AP_sum.cpp
=> Added AP_sum.cpp

python/maths/Factorial.py, python/string algorithms/Reversing a string using Recursion.py
As discussed in the issues section.
Thanks🖤
=> Added two new files

python/backtracking/magnet_puzzle.py
Solved the magnet puzzle problem
=> Magnet puzzle

ml/CNN/Resnets/resnets.py
I did not edit requirements.txt, since PyTorch was used for VGG model. Hope that's fine.
=> added resnets

cpp/backtracking/Rat_in_a_Maze.cpp
=> [See #374] Added Rat_in_a_Maze in cpp

cpp/maths/Find_volumes_of_various_shapes.cpp, cpp/maths/LCM_of_two_numbers.cpp, cpp/maths/Sum_of_Digits.cpp
I have added the solutions to three problems under cpp maths . 
1.Find volumes of various shapes
2.Sum of digits of 2 numbers.
3.LCM of 2 numbers.
=> CPP maths : Solution to 3 problems: Find_volume_of_various_shapes.cpp , sum_of_digits.cpp , LCM_of_two_numbers.cpp

python/backtracking/Rat_in_a_Maze.py
=> [See #373] Added Rat_in_a_maze in python

python/backtracking/N_Queen's_Problem.py
=> [See #373] Added N_Queen's_Problem in python

cpp/backtracking/Hamilton_Cycle.cpp
=> [See #374] Added Hamilton_Cycle in cpp

python/Hamilton_Cycle.py
=> [See #373] Added Hamilton_Cycle in python

python/backtracking/m_Coloring_Problem.py
=> [See #373] Added m_Coloring_Problem in python

ml/Perceptrons/.ipynb_checkpoints/Perceptron_As_XOR_Operator-checkpoint.ipynb, ml/Perceptrons/Perceptron_As_XOR_Operator.ipynb
A detailed Jupyter notebook on the implementation of perceptrons as XOR operator has been added. Kindly review and add it to the project. Thanks a lot for giving the opportunity to contribute.
=> Perceptrons as XOR operator added

python/maths/binomial_coefficient_dp.py, python/maths/sum_of_all_elements_till_nth_row_pascals_triangle.py
Implemented Binomial Coefficients and Sum of n rows of Pascal's Triangle algorithms in Python #197
=> Added math algorithms in Python

cpp/Graphs/prim's_algorithm.cpp
prim's algorithm in the graph is added, kindly review
=> prims_algorithm added

dl/LSTM/lstm.py, dl/LSTM/requirements.txt
Implementation of LSTM model using keras framework also added requirements.txt file.
@geekquad  Kindly take a look.
=> LSTM Model 

python/maths/chinese_remainder_theorem.py, python/maths/gcd_of_digits_of_num.py, python/maths/hoax_number.py, python/maths/power_of_prime_in_n_factorial.py
=> Added more math algorithms implemented in Python

go/graph_algorithms/Floyd_warshall.go
Added file **Floyd_warshall.go** to go/graph_algorithms.
- (for Issue: Floyd-Warshall Algorithm)
=> Added Floyd Warshall algorithm implemented in GO.

python/sorting/cyclic_sort.py
Added the python code for cyclic sort.
=> Added cyclic sort

cpp/strings/KMP_Algorithm.cpp, cpp/strings/Z-Algorithm.cpp
=> Added KMP and Z Algorithm

cpp/Strings/Aho_Corasick.cpp
=> added Aho Corasick algortihm

cpp/Strings/prefix_function.cpp
Prefix function method with testing code included at the end of the file (commented out).
=> add prefix function in cpp

cpp/binary_tree/Binary Search Tree.cpp
Adding super library that contains all sub libraries
=> Adding Library

python/greedy_alogrithms/job_sequencing_problem.py
https://github.com/geekquad/AlgoBook/issues/124
=> feat: job sequencing added to python greedy algorithms

java/sorting/merge-sort.java
=> Merge-Sort

java/sorting/bubble_sort.java, java/sorting/selection_sort.java
=> Select sort

java/sorting/bubble_sort.java
=> BubbleSort

java/searching/jump-search.java, java/sorting/Heap-sort.java, java/sorting/Tree-sort.java
=> Jumpsearch

java/sorting/merge-sort.java, java/sorting/radix-sort.java
=> Radix sort

java/sorting/recursive_bubble_sort.java
Recursive Bubble Sort using Java.
=> Recursive-Bubble-Sort

java/sorting/recursive_bubble_sort.java, java/sorting/recursive_insertion_sort.java
Recursive Insertion Sort in Java
=> Recursive Insertion Sort

java/searching/BFS.java, java/searching/BinarySearch.java, java/searching/LinearSearch.java
Linear Search, Binary Search and BFS
=> Add Searching Algorithms

java/searching/InterpolationSearch.java
=> Interpolation-Search

java/sorting/timsort.java, shellsort.java, topologicalsort.java
Java code for Topological sort.
=> Topologicalsort

cpp/searching/binarysearch.cpp
Please see following ling for the details
of the bug.
https://medium.com/swlh/overflow-bug-in-binary-search-c4d4a824807a
=> Fix possible integer overflow error in C++ binary search.

python/tree/red-black.py, python/tree/splay_tree.py
I added a python splay tree and also fixed some spacing issues with the red-black tree
=> Splay Tree
